<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.11">
  <POU Name="InfluxAddData_10Hz" Id="{dbd45c9a-931e-e7d9-c709-f37398582a5e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION InfluxAddData_10Hz : BOOL
VAR_IN_OUT
	Data			: ST_DATA;
	DataCollector	: FB_InfluxDataCollector;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[// =================== Example:
	DataCollector.AddLreal(	'Test',                      Data.Gps.Inputs.x);
]]></ST>
    </Implementation>
    <LineIds Name="InfluxAddData_10Hz">
      <LineId Id="5" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>